### ISSUE TITLE
Search connected with the graphql

### ISSUE THREAD

**Issue by michal-murawski-90poe** [louisotto/github-react-repos#2]
We already have an in-memory search implementation. As a next step, it could be a good idea to update the query and execute a call to the GH API.

Could you make the query dynamic and accept the search variable? Plus, it might be a good opportunity re-think the current `App.tsx` composition and reduce `useEffects` as we are going to rely on the API responses.

Cheers,
Michal

**Comment by louisotto** [comment]
Hi Michal,

This should be fixed in da3e167e19a330e247e1af0efa189676944f327f

Please let me know if this is what you were after!
